Replace use of rowsums in tidyr episode
datacarpentry/r-socialsci pull request #535
Opened 2024-10-15 21:48 UTC by jessesadler

Close #531 

- Use grouped mutate() instead of rowSums() to create summary columns. This is more in line with tidyverse usage and fixes a mistake in lesson where no household was shown to have 0 items.
- Explain use of grouped mutate() and dplyr `if_else()` function.
- Create new exercise to do the same with months lacking food.
- Remove exercise in pivot longer that replicated earlier calculations in a confusing manner.
- Change code to recreate `interviews_plotting` in ggplot2 episode using new method.
- Change `interviews_plotting` data using new method.

2024-11-05 20:59 UTC, juanfung commented on episodes/04-tidyr.Rmd
> +Make a table showing showing the number of respondents in each village who owned
`showing` appears twice

2024-11-05 21:02 UTC, juanfung requested changes
Looks great! Approve contingent on fixing the one minor typo (left a comment on line 393 of `04-tidyr.Rmd`.

2024-11-06 20:38 UTC, jessesadler commented on episodes/04-tidyr.Rmd
> +Make a table showing showing the number of respondents in each village who owned
Fixed! Good catch.

2024-11-06 20:46 UTC, juanfung approved these changes
Not clear if this is approving the update but...approve!

2024-11-06 20:47 UTC, merged